name: 'Build & Publish'
description: 'Build & Publish'
runs:
  using: 'composite'
  steps:
    - name: Build & publish windows production binaries
      shell: bash
      if: runner.os == 'Windows' && github.ref == 'master' && github.event_name == 'push'
      run: $(yarn bin)/electron-builder --config.extraMetadata.environment=%SIGNAL_ENV% --publish=always

    - name: Build & publish mac production binaries
      shell: bash
      if: runner.os == 'macOS' && github.ref == 'master' && github.event_name == 'push'
      run: |
        source ./build/setup-mac-certificate.sh
        $(yarn bin)/electron-builder --config.extraMetadata.environment=$SIGNAL_ENV --config.mac.bundleVersion=${{ github.ref }} --publish=always
      env:
        MAC_CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
        MAC_CERTIFICATE_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
        SIGNING_APPLE_ID: ${{ secrets.SIGNING_APPLE_ID }}
        SIGNING_APP_PASSWORD: ${{ secrets.SIGNING_APP_PASSWORD }}
        SIGNING_TEAM_ID: ${{ secrets.SIGNING_TEAM_ID }}

    - name: Build & publish linux production binaries
      shell: bash
      if: runner.os == 'Linux' && github.ref == 'master' && github.event_name == 'push'
      run: |
        sudo apt-get install -y rpm
        yarn build-release-publish
