name: 'Build Only (no publish)'
description: 'Build only (no publish)'
inputs:
  MAC_CERTIFICATE:
    description: 'MAC_CERTIFICATE (mac build only)'
    required: true
  MAC_CERTIFICATE_PASSWORD:
    description: 'MAC_CERTIFICATE_PASSWORD (mac build only)'
    required: true
  SIGNING_APPLE_ID:
    description: 'SIGNING_APPLE_ID (mac build only)'
    required: true
  SIGNING_APP_PASSWORD:
    description: 'SIGNING_APP_PASSWORD (mac build only)'
    required: true
  SIGNING_TEAM_ID:
    description: 'SIGNING_TEAM_ID (mac build only)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build windows production binaries
      shell: bash
      if: runner.os == 'Windows'
      run: $(yarn bin)/electron-builder --config.extraMetadata.environment=%SIGNAL_ENV% --publish=never --config.directories.output=release

    - name: Build mac production binaries
      shell: bash
      if: runner.os == 'macOS'
      run: |
        source ./build/setup-mac-certificate.sh
        $(yarn bin)/electron-builder --config.extraMetadata.environment=$SIGNAL_ENV --config.mac.bundleVersion=${{ github.ref }} --publish=never --config.directories.output=release
      env:
        MAC_CERTIFICATE: ${{ inputs.MAC_CERTIFICATE }}
        MAC_CERTIFICATE_PASSWORD: ${{ inputs.MAC_CERTIFICATE_PASSWORD }}
        SIGNING_APPLE_ID: ${{ inputs.SIGNING_APPLE_ID }}
        SIGNING_APP_PASSWORD: ${{ inputs.SIGNING_APP_PASSWORD }}
        SIGNING_TEAM_ID: ${{ inputs.SIGNING_TEAM_ID }}

    - name: Build linux production binaries
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y rpm
        yarn build-release

    - name: Remove unpacked files
      run: |
        ls -d -- */ | xargs -I{} echo "Removing {}"
        ls -d -- */ | xargs -I{} rm -rf {}
      shell: bash
      working-directory: ./release/

    - name: Remaining files
      run: ls .
      shell: bash
      working-directory: ./release/

    - name: Upload Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-${{ runner.arch }}-production
        path: release
